# Generated by Django 6.1.1 on 2026-09-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Аудитория',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер', models.CharField(max_length=10, unique=True, verbose_name='Номер аудитории')),
                ('вместимость', models.IntegerField(default=1, verbose_name='Вместимость')),
                ('тип', models.CharField(choices=[('lecture', 'Лекционная'), ('practice', 'Практическая'), ('lab', 'Лаборатория'), ('office', 'Кабинет преподавателя')], max_length=50, verbose_name='Тип аудитории')),
                ('оборудование', models.TextField(blank=True, verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['номер'],
            },
        ),
        migrations.CreateModel(
            name='Отчет',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('load', 'Отчет по нагрузке'), ('publications', 'Отчет по публикациям'), ('staff', 'Отчет по сотрудникам')], max_length=100, verbose_name='Тип отчета')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('данные', models.TextField(verbose_name='Данные отчета')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-дата_создания'],
            },
        ),
        migrations.CreateModel(
            name='Преподаватель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фио', models.CharField(max_length=200, verbose_name='ФИО')),
                ('должность', models.CharField(max_length=100, verbose_name='Должность')),
                ('ставка', models.FloatField(default=1.0, verbose_name='Размер ставки')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('телефон', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('корпус', models.CharField(blank=True, max_length=10, verbose_name='Корпус')),
                ('этаж', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('аудитория', models.CharField(blank=True, max_length=10, verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['фио'],
            },
        ),
        migrations.CreateModel(
            name='ДополнительнаяНагрузка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('curator', 'Кураторство'), ('practice', 'Руководство практикой'), ('diploma', 'Руководство ВКР'), ('research', 'Научная работа'), ('methodical', 'Методическая работа')], max_length=100, verbose_name='Тип нагрузки')),
                ('описание', models.TextField(verbose_name='Описание')),
                ('часы', models.IntegerField(default=0, verbose_name='Количество часов')),
                ('преподаватель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='доп_нагрузка', to='core.преподаватель', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Дополнительная нагрузка',
                'verbose_name_plural': 'Дополнительные нагрузки',
            },
        ),
        migrations.CreateModel(
            name='Дисциплина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('код', models.CharField(max_length=20, unique=True, verbose_name='Код дисциплины')),
                ('часы_лекций', models.IntegerField(default=0, verbose_name='Часы лекций')),
                ('часы_практик', models.IntegerField(default=0, verbose_name='Часы практик')),
                ('преподаватели', models.ManyToManyField(blank=True, to='core.преподаватель', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['название'],
            },
        ),
        migrations.CreateModel(
            name='Публикация',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=300, verbose_name='Название публикации')),
                ('год', models.IntegerField(verbose_name='Год публикации')),
                ('тип', models.CharField(choices=[('article', 'Статья'), ('conference', 'Конференция'), ('book', 'Книга'), ('patent', 'Патент')], max_length=50, verbose_name='Тип публикации')),
                ('журнал', models.CharField(blank=True, max_length=200, verbose_name='Журнал/Издание')),
                ('страницы', models.CharField(blank=True, max_length=50, verbose_name='Страницы')),
                ('авторы', models.ManyToManyField(related_name='публикации', to='core.преподаватель', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-год', 'название'],
            },
        ),
    ]
