# Generated by Django 6.1.1 on 2026-09-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Бронирование',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('день_недели', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='День недели')),
                ('время_начала', models.TimeField(verbose_name='Время начала')),
                ('время_окончания', models.TimeField(verbose_name='Время окончания')),
                ('тип_занятия', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('exam', 'Экзамен'), ('consultation', 'Консультация'), ('other', 'Другое')], max_length=50, verbose_name='Тип занятия')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('активно', models.BooleanField(default=True, verbose_name='Активно')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('аудитория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='бронирования', to='core.аудитория', verbose_name='Аудитория')),
                ('преподаватель', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='бронирования', to='core.преподаватель', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['день_недели', 'время_начала'],
            },
        ),
    ]
